<?php

namespace Pidev\AllForDealBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppelOffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppelOffreRepository extends EntityRepository
{
        public function findAppelOffre($id) {
        $qb=$this->createQueryBuilder('a')
                ->select('a')
                ->where('a.idConsommateur = (:id)')
                ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
    public function findAppelOffreAll($id) {
        $qb=$this->createQueryBuilder('a')
                ->select('a')
                ->where('a.idConsommateur != (:id)')
                ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }

}
