<?php

namespace Pidev\AllForDealBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository {
    
    public function findArray($array) {
        $qb=$this->createQueryBuilder('c')
                ->select('c')
                ->where('c.idConsommateur IN (:array)')
                ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
}
