<?php

namespace Pidev\AllForDealBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * EvaluationServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationServiceRepository extends EntityRepository
{
    
    public function moyenne($offre) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select("avg(o.rating)")
                        ->from("PidevAllForDealBundle:EvaluationService", "o")
                        ->andWhere("o.idService=:idOffre")->setParameter('idOffre', $offre);

        return $query->getQuery()->getSingleScalarResult();
    }

    public function moyenneAgent($compte) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select("avg(o.rating)")
                        ->from("PidevAllForDealBundle:EvaluationService", "o")
                        ->andWhere("o.idMembre=:idAgent")->setParameter('idAgent', $compte);

        return $query->getQuery()->getSingleScalarResult();
    }
}
