<?php

namespace Pidev\AllForDealBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository {

    public function findFirst($id) {

        $qb = $this->createQueryBuilder('i')
                ->select('i')
                ->where('i.idProduit = :id')
                ->setParameter('id', $id)
                ->setMaxResults(1);
        return $qb->getQuery()->getSingleResult();
    }

}
