<?php

namespace Pidev\AllForDealBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LigneCmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneCmdRepository extends EntityRepository {

    public function findByOrder($id) {
        $qb = $this->createQueryBuilder('l')
                ->select('l')
                ->where('l.idCommande IN (:id)')
                ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }

}
