<?php

namespace Pidev\AllForDealBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository {

    public function findLike($filter) {
        $query = $this
                ->getEntityManager()
                ->createQuery("SELECT m FROM PidevAllForDealBundle:Membre m WHERE m.nom like '%" . $filter . "%' OR m.prenom LIKE  '%" . $filter . "%'");
        return $query->getResult();
    }

}
