services:
    imageExtension:
        class: Pidev\AllForDealBundle\Twig\Extension\ImageExtension
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: twig.extension }
    
    cartExtension:
        class: Pidev\AllForDealBundle\Twig\Extension\CartExtension
        arguments: [ @session ]
        tags:
            - { name: twig.extension }
    
    redirectionListener:
        class: Pidev\AllForDealBundle\Listener\RedirectionListener
        arguments: [ @service_container, @session ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
